version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/Heroicons.AspNetCore.Mvc.TagHelpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
